### ISSUE TITLE
Node.js error at running index.js : app.get('/callback', async (req, res) => {

### ISSUE THREAD

**Issue by arioboo** [lichess-org/api#62]
Hello, I have configured my lichess account to have an oauth app and a personal API token.
When I was following the instructions of the oauth_app example, the following happened when I ran "node index.js"

```
app.get('/callback', async (req, res) => {
                           ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
```

I have no idea of how to handle this error, and I'm new to nodejs. A better documentation or a quick help would be needed.

**Comment by casalazara** [comment]
I'm also new to nodejs but maybe trying with " async function (req, res) => { " would work or trying to replace those characters like " " or ' ', it might be a problem of the encoding, for example some "" that were copied in another format

**Comment by niklasf** [comment]
You're probably running a very old nodejs. Updated the example to specify a minimum version.
