### ISSUE TITLE
board api error in running "yarn start" by following READMD.md

### ISSUE THREAD

**Issue by jingwenw** [lichess-org/api#86]
In config.ts, it is the port of 8080, while in README.md is 8087? 

And "yarn start" only can be executed under back/ subdir, and with the following error:

/home/james/myRepos/wjw/lila_api/example/board-api/back/src/router.ts:25
        const auth = await env.mongo.auth.get(req.session?.authId || '');
                                                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.m._compile (/home/james/myRepos/wjw/lila_api/example/board-api/back/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/home/james/myRepos/wjw/lila_api/example/board-api/back/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/james/myRepos/wjw/lila_api/example/board-api/back/src/index.ts:6:1)
[nodemon] app crashed - waiting for file changes before starting...

Thank

**Comment by ornicar** [comment]
Thanks, fixed and improved

**Comment by jingwenw** [comment]
Thanks for your quick response and support - the instructions in READM.md is so clear, very professional!

But after updating this repo, and follow READM.dm, I still get the error when yarn start:

james@vsbox16:~/myRepos/wjw/lila-api/example/board-api/front$ cd ../back/
james@vsbox16:~/myRepos/wjw/lila-api/example/board-api/back$ yarn install
yarn install v1.22.10
warning ../package.json: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.37s.
james@vsbox16:~/myRepos/wjw/lila-api/example/board-api/back$ yarn start
yarn run v1.22.10
warning ../package.json: No license field
$ nodemon src/index.ts
[nodemon] 2.0.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`
/home/james/myRepos/wjw/lila-api/example/board-api/back/src/router.ts:25
        const auth = await env.mongo.auth.get(req.session?.authId || '');
                                                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.m._compile (/home/james/myRepos/wjw/lila-api/example/board-api/back/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/home/james/myRepos/wjw/lila-api/example/board-api/back/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/james/myRepos/wjw/lila-api/example/board-api/back/src/index.ts:6:1)
[nodemon] app crashed - waiting for file changes before starting...

Thanks,
James

**Comment by ornicar** [comment]
hmm idk, can't reproduce it. What does `ts-node --version` say?

**Comment by jingwenw** [comment]
$ ts-node --version
ts-node: command not found

So it seems ts-node is missing in my evn?

Thanks

**Comment by jingwenw** [comment]
Now I installed ts-node v9.1.1 and still see the error:

james@vsbox16:~/myRepos/wjw/lila-api/example/board-api/back$ ts-node
ts-node                 ts-node-script          ts-node-transpile-only
james@vsbox16:~/myRepos/wjw/lila-api/example/board-api/back$ ts-node -v
v9.1.1
james@vsbox16:~/myRepos/wjw/lila-api/example/board-api/back$ yarn install
yarn install v1.22.10
warning ../package.json: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.33s.
james@vsbox16:~/myRepos/wjw/lila-api/example/board-api/back$ yarn start
yarn run v1.22.10
warning ../package.json: No license field
$ nodemon src/index.ts
[nodemon] 2.0.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`
/home/james/myRepos/wjw/lila-api/example/board-api/back/src/router.ts:25
        const auth = await env.mongo.auth.get(req.session?.authId || '');
                                                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.m._compile (/home/james/myRepos/wjw/lila-api/example/board-api/back/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/home/james/myRepos/wjw/lila-api/example/board-api/back/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/james/myRepos/wjw/lila-api/example/board-api/back/src/index.ts:6:1)
[nodemon] app crashed - waiting for file changes before starting...

^C
james@vsbox16:~/myRepos/wjw/lila-api/example/board-api/back$ 

Thanks,

**Comment by jingwenw** [comment]
And nodejs is 12.20.1:

james@vsbox16:~/myRepos/wjw/lila-api/example/board-api/back$ node -v
v12.20.1
james@vsbox16:~/myRepos/wjw/lila-api/example/board-api/back$
